"""Fixed screen/PDF labels in English and Tamil (the AI only translates the report text)."""

TAMIL_RANGE = ("஀", "௿")

LABELS = {
    "English": {
        "report_title": "Personal Health Report",
        "summary": "Summary",
        "normal_results": "Good news: normal results",
        "normal_line": "{test}: {value} is within the normal range ({range})",
        "needs_attention": "What needs attention",
        "your_value_line": "Your value: {value}  ·  Normal for you: {range}  ·  {status}",
        "what_measures": "What this test measures",
        "possible_causes": "Possible causes",
        "food_tips": "Food & lifestyle tips",
        "doctor_may": "What your doctor may do",
        "diet": "Diet & lifestyle",
        "questions": "Questions to ask your doctor",
        "warning": "See a doctor quickly if you notice",
        "medicines": "Your medicines",
        "used_for": "Usually used for",
        "how_to_take": "How to take (as written)",
        "side_effects": "Common side effects",
        "precautions": "Precautions",
        "meds_caution": "Do not start, stop or change any medicine without asking your doctor.",
        "no_meds": "No medicines in this document.",
        "test_results": "Test results",
        "test": "Test", "your_value": "Your value", "normal_range": "Normal range (your age/sex)",
        "status": "Status", "note": "Note",
        "tests_checked": "Tests checked", "normal": "Normal", "need_attention": "Need attention",
        "critical_alert": "Some values are far outside the normal range: {tests}. Please contact your doctor today.",
        "tab_report": "📋 Simple report", "tab_tests": "🧪 Test results",
        "tab_meds": "💊 Medicines", "tab_data": "🗂️ Extracted data",
        "download_pdf": "⬇️ Download report (PDF)",
        "translating": "Translating the report...",
        "disclaimer": ("This report explains your document in simple words. It is not a diagnosis "
                       "or a prescription. Always follow your doctor's advice."),
        "document": "Document", "date": "Date", "doctor": "Doctor", "lab": "Lab/Hospital",
        "generated": "Generated by Personal Health Copilot",
        "profile": {"name": "Name", "age": "Age", "sex": "Sex", "weight": "Weight",
                    "height": "Height", "bmi": "BMI"},
        "status_names": {"NORMAL": "Normal", "LOW": "Low", "HIGH": "High",
                         "CRITICAL LOW": "Critical low", "CRITICAL HIGH": "Critical high",
                         "TEXT": "Descriptive", "UNKNOWN": "Unknown"},
        "urgency": {"routine": "Routine", "see_doctor_soon": "See your doctor soon",
                    "urgent": "Urgent: contact a doctor today"},
        "sex_values": {"male": "Male", "female": "Female"},
        "bmi_cat": {"Underweight": "Underweight", "Normal": "Normal",
                    "Overweight": "Overweight", "Obese": "Obese"},
        "years": "years",
    },
    "Tamil": {
        "report_title": "தனிப்பட்ட சுகாதார அறிக்கை",
        "summary": "சுருக்கம்",
        "normal_results": "நல்ல செய்தி: இயல்பான முடிவுகள்",
        "normal_line": "{test}: {value} - இயல்பு அளவுக்குள் உள்ளது ({range})",
        "needs_attention": "கவனிக்க வேண்டியவை",
        "your_value_line": "உங்கள் மதிப்பு: {value}  ·  உங்களுக்கான இயல்பு அளவு: {range}  ·  {status}",
        "what_measures": "இந்த பரிசோதனை எதை அளவிடுகிறது",
        "possible_causes": "சாத்தியமான காரணங்கள்",
        "food_tips": "உணவு மற்றும் வாழ்க்கை முறை குறிப்புகள்",
        "doctor_may": "உங்கள் மருத்துவர் செய்யக்கூடியவை",
        "diet": "உணவு மற்றும் வாழ்க்கை முறை",
        "questions": "உங்கள் மருத்துவரிடம் கேட்க வேண்டிய கேள்விகள்",
        "warning": "இவற்றை கவனித்தால் உடனே மருத்துவரை அணுகவும்",
        "medicines": "உங்கள் மருந்துகள்",
        "used_for": "பொதுவாக பயன்படுத்தப்படுவது",
        "how_to_take": "எப்படி எடுக்க வேண்டும் (எழுதியபடி)",
        "side_effects": "பொதுவான பக்க விளைவுகள்",
        "precautions": "முன்னெச்சரிக்கைகள்",
        "meds_caution": "உங்கள் மருத்துவரிடம் கேட்காமல் எந்த மருந்தையும் தொடங்கவோ, நிறுத்தவோ, மாற்றவோ வேண்டாம்.",
        "no_meds": "இந்த ஆவணத்தில் மருந்துகள் இல்லை.",
        "test_results": "பரிசோதனை முடிவுகள்",
        "test": "பரிசோதனை", "your_value": "உங்கள் மதிப்பு", "normal_range": "இயல்பு அளவு",
        "status": "நிலை", "note": "குறிப்பு",
        "tests_checked": "சரிபார்த்த பரிசோதனைகள்", "normal": "இயல்பு", "need_attention": "கவனிக்க வேண்டியவை",
        "critical_alert": "சில மதிப்புகள் இயல்பு அளவை விட மிகவும் வேறுபடுகின்றன: {tests}. இன்றே உங்கள் மருத்துவரை தொடர்பு கொள்ளவும்.",
        "tab_report": "📋 எளிய அறிக்கை", "tab_tests": "🧪 பரிசோதனை முடிவுகள்",
        "tab_meds": "💊 மருந்துகள்", "tab_data": "🗂️ பிரித்தெடுத்த தரவு",
        "download_pdf": "⬇️ அறிக்கையை பதிவிறக்கவும் (PDF)",
        "translating": "அறிக்கையை தமிழில் மொழிபெயர்க்கிறது...",
        "disclaimer": ("இந்த அறிக்கை உங்கள் ஆவணத்தை எளிய சொற்களில் விளக்குகிறது. இது நோயறிதலோ "
                       "மருந்துச் சீட்டோ அல்ல. எப்போதும் உங்கள் மருத்துவரின் ஆலோசனையைப் பின்பற்றவும்."),
        "document": "ஆவணம்", "date": "தேதி", "doctor": "மருத்துவர்", "lab": "ஆய்வகம்/மருத்துவமனை",
        "generated": "Personal Health Copilot உருவாக்கியது",
        "profile": {"name": "பெயர்", "age": "வயது", "sex": "பாலினம்", "weight": "எடை",
                    "height": "உயரம்", "bmi": "BMI"},
        "status_names": {"NORMAL": "இயல்பு", "LOW": "குறைவு", "HIGH": "அதிகம்",
                         "CRITICAL LOW": "மிகக் குறைவு", "CRITICAL HIGH": "மிக அதிகம்",
                         "TEXT": "விளக்கம்", "UNKNOWN": "தெரியவில்லை"},
        "urgency": {"routine": "வழக்கமானது", "see_doctor_soon": "விரைவில் மருத்துவரை அணுகவும்",
                    "urgent": "அவசரம்: இன்றே மருத்துவரை அணுகவும்"},
        "sex_values": {"male": "ஆண்", "female": "பெண்"},
        "bmi_cat": {"Underweight": "குறைந்த எடை", "Normal": "இயல்பு",
                    "Overweight": "அதிக எடை", "Obese": "உடல் பருமன்"},
        "years": "வயது",
    },
}


def has_tamil(text: str) -> bool:
    return any(TAMIL_RANGE[0] <= ch <= TAMIL_RANGE[1] for ch in text)


def num(v: float) -> str:
    """15 -> '15', 41.67 -> '41.67', 1550000 -> '1,550,000' (never 1.55e+06)."""
    if abs(v) >= 10000:
        return f"{v:,.0f}"
    return f"{v:.2f}".rstrip("0").rstrip(".") if v != int(v) else str(int(v))


def fmt_range(f) -> str:
    if f.low is not None and f.high is not None:
        return f"{num(f.low)} - {num(f.high)} {f.unit}".strip()
    if f.high is not None:
        return f"< {num(f.high)} {f.unit}".strip()
    if f.low is not None:
        return f"> {num(f.low)} {f.unit}".strip()
    return "-"


def fmt_value(f) -> str:
    return f"{num(f.value)} {f.unit}".strip() if f.value is not None else (f.value_text or "-")


def profile_lines(profile: dict, language: str) -> list[tuple[str, str]]:
    """profile uses internal keys: name, age, sex, weight, height, bmi, bmi_cat."""
    L = LABELS[language]
    out = []
    if profile.get("name"):
        out.append((L["profile"]["name"], profile["name"]))
    if profile.get("age"):
        out.append((L["profile"]["age"], f"{profile['age']:g} {L['years']}"))
    if profile.get("sex"):
        out.append((L["profile"]["sex"], L["sex_values"].get(profile["sex"].lower(), profile["sex"])))
    if profile.get("weight"):
        out.append((L["profile"]["weight"], f"{profile['weight']:g} kg"))
    if profile.get("height"):
        out.append((L["profile"]["height"], f"{profile['height']:g} cm"))
    if profile.get("bmi"):
        out.append((L["profile"]["bmi"], f"{profile['bmi']} ({L['bmi_cat'].get(profile['bmi_cat'], profile['bmi_cat'])})"))
    return out